### ISSUE TITLE
Update this guide with Boot 2.3 features

### ISSUE THREAD

**Issue by philwebb** [spring-guides/gs-spring-boot-docker#84]

**Comment by dsyer** [comment]
Already done (over a week ago). Did you miss it, or did I do it wrong?

**Comment by edudar** [comment]
Could this be about buildpacks support? [Packaging OCI Images](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#build-image) paints quite a different picture with no Dockerfile in sight, for example.

**Comment by dsyer** [comment]
What was “this” in your comment? The guide already has buildpack examples (and links to more detailed documentation like the one you mentioned). Maybe you have some ideas to make them more obvious?

**Comment by edudar** [comment]
"This" just refers to this issue. 

I think it might help to define options that developers have from the start as in Table of Content style. Something in the lines of "You can build nice and shiny spring boot image in the following ways: * dockerfile, * buildpacks using maven/gradle, * jib using its own plugins, * ..." and then expand each bullet point/option with more details. Because what may happen now, is that the developer goes through a tutorial that starts with a lengthy explanation of how to setup Dockerfile properly. They do it step by step. They end up with said Dockerfile and then, if careful, they might see that they didn't actually have to setup Dockerfile manually because there are other options. Or, as happened in my team, they will use `bootBuildImage` **and** `Dockerfile` together.

**Comment by dsyer** [comment]
OK, that’s useful detail. How about opening a new issue?
